/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
Title: React logo
*/

import React from 'react'
import { Float, useGLTF } from '@react-three/drei'
import * as THREE from "three"

const ReactLogo: React.FC<JSX.IntrinsicElements['mesh']> = (props) =>{
    const { nodes, materials } = useGLTF('/models/react.glb')
    return (
      <Float  dispose={null}>
        <group position={[4, 2, 0]}  scale={0.2} dispose={null} >
          <mesh
          {...props}
            castShadow
            receiveShadow
            geometry={(nodes['React-Logo_Material002_0']  as THREE.Mesh).geometry}
            material={materials['Material.002']}
          />
        </group>
      </Float>
    )
  }

useGLTF.preload('/models/react.glb')

export default ReactLogo